import Link from 'next/link'
import { AppShell, PageTitle } from '@/components/AppShell'
import { createAdminClient } from '@/lib/supabase/admin'
import { requireAdmin } from '@/lib/auth'

export default async function AttemptDetail({params}:{params:Promise<{attemptId:string}>}){
 await requireAdmin(); const {attemptId}=await params; const db=createAdminClient() as any
 const {data:a}=await db.from('attempts').select('*').eq('id',attemptId).maybeSingle(); if(!a)return <AppShell role="admin"><PageTitle eyebrow="Admin / Attempts" title="Attempt not found"/></AppShell>
 const [{data:u},{data:ass},{data:answers},{data:snaps}]=await Promise.all([db.from('profiles').select('full_name').eq('id',a.user_id).maybeSingle(),db.from('assessments').select('name,passing_score').eq('id',a.assessment_id).maybeSingle(),db.from('attempt_answers').select('question_id,answer,score,is_correct,feedback,time_spent_sec,reviewed,requires_review,grading_status').eq('attempt_id',attemptId),db.from('attempt_question_snapshots').select('question_id,question_snapshot').eq('attempt_id',attemptId)])
 const am=new Map<string,any>((answers??[]).map((x:any)=>[x.question_id,x] as [string,any])); return <AppShell role="admin"><div className="flex flex-wrap items-end justify-between gap-4"><PageTitle eyebrow="Admin / Attempt detail" title={u?.full_name||a.user_id} desc={`${ass?.name||a.assessment_id} · ${a.status}`}/><a className="btn-secondary" href={`/api/admin/attempts/${attemptId}/export`}>Export Excel</a></div><div className="grid gap-4 md:grid-cols-4"><div className="card p-5"><b>{a.score}/{a.max_score}</b><div className="text-xs text-slate-500">Score</div></div><div className="card p-5"><b>{a.duration_sec??0}s</b><div className="text-xs text-slate-500">Time used</div></div><div className="card p-5"><b>{a.status}</b><div className="text-xs text-slate-500">Status</div></div><div className="card p-5"><b>{ass?.passing_score??60}%</b><div className="text-xs text-slate-500">Pass mark</div></div></div><div className="mt-5 card overflow-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="px-5 py-4">Question</th><th className="px-5 py-4">Answer</th><th className="px-5 py-4">Score</th><th className="px-5 py-4">Time</th><th className="px-5 py-4">Grade</th><th className="px-5 py-4">Review</th></tr></thead><tbody>{(snaps??[]).map((s:any,i:number)=>{const q=s.question_snapshot||{};const x=am.get(s.question_id);return <tr key={s.question_id} className="border-t border-line"><td className="px-5 py-4"><b>Q{i+1}. {q.title}</b><div className="text-xs text-slate-500">{q.marks} marks</div></td><td className="max-w-md px-5 py-4 whitespace-pre-wrap text-slate-400">{x?.answer||'—'}</td><td className="px-5 py-4">{x?.score??0}/{q.marks}</td><td className="px-5 py-4">{x?.time_spent_sec??0}s</td><td className="px-5 py-4">{x?.is_correct===true?'Correct':x?.is_correct===false?'Incorrect':'Pending'}</td><td className="px-5 py-4">{x?.requires_review?'Needs review':x?.reviewed?'Reviewed':'—'}</td></tr>})}</tbody></table></div><Link className="btn-secondary mt-5 inline-block" href="/admin/attempts">Back</Link></AppShell>
}
