'use client'

import { useEffect, useState } from 'react'
import { AppShell, PageTitle } from '@/components/AppShell'

export default function NewQuestionPage(){
  const [f,setF]=useState({id:'',programId:'sql',topic:'',title:'',prompt:'',questionType:'sql',difficulty:'easy',marks:5,timeLimitSec:180,answerKey:'',starterCode:'',graderConfig:'{}',choices:''})
  const [msg,setMsg]=useState('')
  const [programs,setPrograms]=useState<{id:string;name:string}[]>([])
  useEffect(()=>{void fetch('/api/admin/programs').then(r=>r.json()).then(j=>setPrograms(j.programs??[])).catch(()=>setPrograms([]))},[])
  const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
  const needsChoices=['mcq','multi_select','true_false'].includes(f.questionType)
  async function submit(e:React.FormEvent){e.preventDefault();let graderConfig:Record<string,unknown>;try{graderConfig=JSON.parse(f.graderConfig||'{}')}catch{setMsg('Grader config must be valid JSON.');return}const choices=f.choices.split('\n').map(c=>c.trim()).filter(Boolean);if(needsChoices&&choices.length<2){setMsg('MCQ/multi-select/true-false questions need at least 2 choices.');return}setMsg('Saving…');const res=await fetch('/api/admin/questions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...f,marks:Number(f.marks),timeLimitSec:Number(f.timeLimitSec),graderConfig,choices:choices.length?choices:null})});const j=await res.json();setMsg(res.ok?`Saved ${j.count} question.`:j.error)}
  return <AppShell role="admin"><PageTitle eyebrow="Admin / Questions" title="Create question" desc="Use this form for individual questions. For a large bank, use Bulk Import."/><form onSubmit={submit} className="card p-6 space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="ID" value={f.id} set={v=>set('id',v)}/><Field label="Topic" value={f.topic} set={v=>set('topic',v)}/><Field label="Title" value={f.title} set={v=>set('title',v)}/><Select label="Program" value={f.programId} set={v=>set('programId',v)} options={programs.map(p=>p.id)}/><Select label="Question type" value={f.questionType} set={v=>set('questionType',v)} options={['sql','excel','python','code','data_engineering','case_study','mcq','multi_select','true_false','text','numeric','manual_review']}/><Select label="Difficulty" value={f.difficulty} set={v=>set('difficulty',v)} options={['easy','medium','hard']}/><Field label="Marks" value={String(f.marks)} set={v=>set('marks',v)} type="number"/><Field label="Time limit (sec)" value={String(f.timeLimitSec)} set={v=>set('timeLimitSec',v)} type="number"/></div><label className="block"><span className="label">Prompt</span><textarea className="input min-h-32" value={f.prompt} onChange={e=>set('prompt',e.target.value)} required/></label>{needsChoices && <label className="block"><span className="label">Choices (one per line)</span><textarea className="input min-h-28" value={f.choices} onChange={e=>set('choices',e.target.value)} placeholder={'Option A\nOption B\nOption C'} required/></label>}<label className="block"><span className="label">Starter code</span><textarea className="input min-h-36 font-mono" value={f.starterCode} onChange={e=>set('starterCode',e.target.value)}/></label><label className="block"><span className="label">Grader config JSON</span><textarea className="input min-h-28 font-mono" value={f.graderConfig} onChange={e=>set('graderConfig',e.target.value)} placeholder='For Excel: {"sheets":{"Sheet1":[[1,2]]},"expected":{"Sheet1!C1":{"formula":"=A1+B1","value":3}}}' /></label><label className="block"><span className="label">Answer key</span><textarea className="input min-h-28 font-mono" value={f.answerKey} onChange={e=>set('answerKey',e.target.value)} required/></label><div className="flex items-center gap-3"><button className="btn-primary">Save as draft</button>{msg && <span className="text-sm text-slate-400">{msg}</span>}</div></form></AppShell>
}
function Field({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block"><span className="label">{label}</span><input className="input" type={type} value={value} onChange={e=>set(e.target.value)} required/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <label className="block"><span className="label">{label}</span><select className="input" value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
