'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

const ADMIN_EMAIL='soumyaranjanliku16@gmail.com'

export default function AdminCreatePasswordPage(){
  const [email,setEmail]=useState(ADMIN_EMAIL); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false)
  useEffect(()=>{void createClient().auth.getUser().then(({data})=>{if(data.user?.email?.toLowerCase()===ADMIN_EMAIL&&data.user.email_confirmed_at)setSent(true)})},[])
  async function requestVerification(e:React.FormEvent){e.preventDefault();setError('');if(email.trim().toLowerCase()!==ADMIN_EMAIL)return setError('Only the authorized admin email can use this setup.');if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return setError('Authentication is not configured yet.');setBusy(true);const supabase=createClient();const temporary=crypto.randomUUID()+'Aa1!';const {error}=await supabase.auth.signUp({email:ADMIN_EMAIL,password:temporary,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/admin/create-password`}});if(!error){setSent(true);setBusy(false);return}if(/already registered|already exists/i.test(error.message)){const {error:resendError}=await supabase.auth.resend({type:'signup',email:ADMIN_EMAIL,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/admin/create-password`}});if(!resendError){setSent(true);setBusy(false);return}const {error:recoveryError}=await supabase.auth.resetPasswordForEmail(ADMIN_EMAIL,{redirectTo:`${window.location.origin}/auth/callback?next=/admin/create-password`});if(!recoveryError){setSent(true);setBusy(false);return}setError('We could not send the admin verification email. Please try again later.');setBusy(false);return}setError(error.message);setBusy(false)}
  async function createPassword(e:React.FormEvent){e.preventDefault();setError('');if(password.length<12)return setError('Use at least 12 characters.');if(password!==confirm)return setError("Passwords don't match.");setBusy(true);const supabase=createClient();const {data}=await supabase.auth.getUser();if(data.user?.email?.toLowerCase()!==ADMIN_EMAIL||!data.user.email_confirmed_at){setError('Verify the admin email before creating the password.');setBusy(false);return}const {error}=await supabase.auth.updateUser({password});if(error){setError(error.message);setBusy(false);return}const res=await fetch('/api/admin/bootstrap',{method:'POST'});const json=await res.json();if(!res.ok){setError(json.error||'Could not create the admin account.');setBusy(false);return}window.location.href='/admin/dashboard'}
  return <main className="grid min-h-screen place-items-center bg-slate-950 px-5 py-10"><div className="w-full max-w-md"><Link href="/" className="text-lg font-black text-white">Skill<span className="text-violet-400">Forge</span></Link><div className="mt-8 rounded-3xl border border-white/10 bg-white p-7"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-brand/10 text-2xl">♛</div><h1 className="mt-5 text-center text-2xl font-black text-slate-900">Set your admin password</h1><p className="mt-2 text-center text-sm leading-6 text-slate-500">Verify the authorized admin email first, then choose a secure password.</p>{!sent?<form onSubmit={requestVerification} className="mt-6 space-y-4"><label className="block"><span className="label">Admin email</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><button className="btn-primary w-full" disabled={busy}>{busy?'Sending…':'Send verification email'}</button></form>:<form onSubmit={createPassword} className="mt-6 space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">Verification email sent to <b>{ADMIN_EMAIL}</b>. After clicking it, return here to create your password.</div><label className="block"><span className="label">New admin password</span><input className="input" type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required /></label><label className="block"><span className="label">Confirm password</span><input className="input" type="password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} required /></label>{error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-600">{error}</div>}<button className="btn-primary w-full" disabled={busy}>{busy?'Creating…':'Create admin account'}</button></form>}<div className="mt-5 text-center text-sm"><Link href="/admin/login" className="text-brand">Back to admin login</Link></div></div></div></main>
}
