import Link from 'next/link'
import { AppShell, PageTitle } from '@/components/AppShell'
import { createAdminClient } from '@/lib/supabase/admin'
import { requireAdmin } from '@/lib/auth'
import { UserActions } from './user-actions'

export default async function AdminUsers({searchParams}:{searchParams:Promise<{page?:string}>}){
 await requireAdmin(); const page=Math.max(1,Number((await searchParams).page)||1); const perPage=50; const db=createAdminClient() as any
 const auth=await db.auth.admin.listUsers({page,perPage}); const users=auth.data?.users??[]; const ids=users.map((u:any)=>u.id)
 const [{data:profiles},{data:attempts},{data:assessments}]=await Promise.all([db.from('profiles').select('id,full_name,role,status,created_at').in('id',ids),ids.length?db.from('attempts').select('user_id,assessment_id,score,max_score,status,duration_sec').in('user_id',ids):{data:[]},db.from('assessments').select('id,passing_score')])
 const emails=new Map<string,string>(users.map((u:any)=>[u.id,u.email] as [string,string])); const thresholds=new Map((assessments??[]).map((x:any)=>[x.id,Number(x.passing_score)])); const by=new Map<string,any[]>(); for(const x of attempts??[])(by.get(x.user_id)||by.set(x.user_id,[]).get(x.user_id)!).push(x)
 return <AppShell role="admin"><PageTitle eyebrow="Admin / Users" title="User management" desc="Paginated live profiles, access status and assessment performance."/><div className="card overflow-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-[.12em] text-slate-500"><tr>{['Name','Email','Role','Status','Attempts','Avg score','Pass rate','Created','Access'].map(x=><th className="px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody>{(profiles??[]).map((p:any)=>{const xs=by.get(p.id)??[];const done=xs.filter(x=>['auto_graded','approved','released'].includes(x.status));const avg=done.length?done.reduce((n,x)=>n+Number(x.max_score?x.score/x.max_score*100:0),0)/done.length:0;const pass=done.length?done.filter(x=>x.max_score&&x.score/x.max_score*100>=Number(thresholds.get(x.assessment_id)??60)).length/done.length*100:0;return <tr key={p.id} className="border-t border-line"><td className="px-5 py-4 font-semibold"><Link className="text-brand hover:underline" href={`/admin/users/${p.id}`}>{p.full_name||'Unnamed'}</Link></td><td className="px-5 py-4 text-slate-400">{emails.get(p.id)??'—'}</td><td className="px-5 py-4">{p.role}</td><td className="px-5 py-4">{p.status}</td><td className="px-5 py-4">{xs.length}</td><td className="px-5 py-4">{avg.toFixed(1)}%</td><td className="px-5 py-4">{pass.toFixed(1)}%</td><td className="px-5 py-4 text-slate-500">{new Date(p.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><UserActions userId={p.id} status={p.status}/></td></tr>})}</tbody></table></div><div className="mt-4 flex gap-3">{page>1&&<Link className="btn-secondary" href={`/admin/users?page=${page-1}`}>Previous</Link>}{users.length===perPage&&<Link className="btn-secondary" href={`/admin/users?page=${page+1}`}>Next</Link>}</div></AppShell>
}
